# Generated by Django 5.2.4 on 2025-07-30 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivery partner assigned to this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="pending_sync",
            field=models.BooleanField(
                default=False, help_text="Indicates if this request was created offline"
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
