# Generated by Django 5.2.4 on 2025-07-31 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delivery",
            "0003_deliveryrequest_partner_deliveryrequest_pending_sync_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryrequest",
            name="partner",
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who assigned the driver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="customer",
            field=models.ForeignKey(
                default=None,
                help_text="Customer who created this request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver assigned to this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
