# Generated by Django 5.2.4 on 2025-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("driver", "Driver"),
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
